### ISSUE TITLE
File ordering

### ISSUE THREAD

**Issue by joliss** [logicalparadox/folio#1]
We're distributing the compiled chai.js in Konacha, and we're getting massive diffs, presumably because the ordering of the included files is random. I'm assuming that

```
.dir('./lib')
```

is the culprit. I can't find the right place in folio to fix this, but IMO it could and should just sort everything alphabetically, rather than relying on file system order.

**Comment by logicalparadox** [comment]
Yeah, can see how that can be akward. I'll see what I can do.

**Comment by logicalparadox** [comment]
That should do it. You'll have to deal with one more big diff as I don't think the os got it right last time around, but it will be stable there after.

**Comment by joliss** [comment]
Awesome, thank you!
